export const TODO_LIST_ITEM_CREATE = 'TODO_LIST_ITEM_CREATE';
export const TODO_LIST_ITEM_UPDATE = 'TODO_LIST_ITEM_UPDATE';
export const TODO_LIST_ITEM_DELETE = 'TODO_LIST_ITEM_DELETE';
export const TODO_LIST_ITEM_MOVE = 'TODO_LIST_ITEM_MOVE';
export const TODO_LIST_ITEM_START_EDITING = 'TODO_LIST_ITEM_START_EDITING';
export const TODO_LIST_ITEM_CANCEL_EDITING = 'TODO_LIST_ITEM_CANCEL_EDITING';
